// <auto-generated />
namespace Resturant.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class inadd : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(inadd));
        
        string IMigrationMetadata.Id
        {
            get { return "201910202002479_inadd"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
